# System
replicaCount: 1

nameOverride: ""
fullnameOverride: ""

images:
  owgwui:
    repository: tip-tip-wlan-cloud-ucentral.jfrog.io/owgw-ui
    tag: main
    pullPolicy: Always

services:
  owgwui:
    type: ClusterIP
    ports:
      http:
        servicePort: 80
        targetPort: 80
        protocol: TCP

checks:
  owgwui:
    liveness:
      httpGet:
        path: /
        port: http
    readiness:
      httpGet:
        path: /
        port: http

ingresses:
  default:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # tls:
    # - secretName: '{{ include "owgwui.fullname" . }}-default-tls' # template may be used
    #   cert: |
    #     CERT_HERE_IN_PEM
    #   key: |
    #     KEY_HERE_IN_PEM
    #   hosts:
    #     - chart-example.local
    hosts:
    - chart-example.local
    paths:
    - path: /
      serviceName: owgwui
      servicePort: http

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  # limits:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Application
public_env_variables:
  DEFAULT_UCENTRALSEC_URL: https://ucentral.dpaas.arilia.com:16001
  ALLOW_UCENTRALSEC_CHANGE: false
