name: Clean up PR Docker images

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

defaults:
  run:
    shell: bash

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          export PR_BRANCH_TAG=$(echo ${GITHUB_HEAD_REF#refs/heads/} | tr '/' '-')
          curl -uucentral:${{ secrets.DOCKER_REGISTRY_PASSWORD }} -X DELETE "https://tip.jfrog.io/artifactory/tip-wlan-cloud-ucentral/owgw-ui/$PR_BRANCH_TAG"
